  create table app.a05_commend_brand (    
       the_month        string     comment'月份'
      ,projectguid      string     comment'项目ID'
      ,projectname      string     comment'项目名称'
      ,city             string     comment'城市'
      ,province         string     comment'省份'
      ,district_name    string     comment'片区'
      ,companyguid      string     comment'公司guid'
      ,companyname      string     comment'公司名称'
      ,is_confilling    string     comment'是否已归档'                       
      ,is_yrent         string     comment'是否已出租'                        
      ,is_jprent        string     comment'是否已接铺'                       
      ,is_openrent      string     comment'是否已开业'                       
      ,brandid          string     comment'品牌ID'
      ,brand_name       string     comment'品牌名称'
      ,totalarea        string     comment'合同面积'
      ,jyn_jyts         string     comment'近一年经营天数'
      ,amt_sum          string     comment'近一年营业额'
      ,customer         string     comment'近一年客流人数'
      ,customer_days    string     comment'近一年有客流天数'
      ,bd_income_y      string     comment'含税保底'
      ,taking_income_y  string     comment'含税抽成'
      ,mng_income_y     string     comment'含税物业'
      ,tg_income_y      string     comment'含税推广'
      ,bd_income_n      string     comment'不含税保底'
      ,taking_income_n  string     comment'不含税抽成'
      ,mng_income_n     string     comment'不含税物业'
      ,tg_income_n      string     comment'不含税推广'
      ,op_time          string     comment'时间戳'
      ,execution_id     string     comment'批次号'
      ,load_date        string     comment'入库时间'
)
 partitioned by
 (datekey string comment '年月分区')
STORED AS PARQUET;