CREATE TABLE raqsoft.smartbi_finance(
      the_year             varchar(20)    comment'年'
     ,the_month            varchar(20)    comment'年月'
     ,regionname           varchar(50)    comment'地区名称'
     ,projectname          varchar(50)    comment'项目名称'
     ,expenditureid        varchar(50)    comment'费项id'
     ,expenditurename      varchar(50)    comment'费项名称'
     ,last_month           decimal(18,6)  comment'上月实际'
     ,cur_month            decimal(18,6)  comment'当月实际'
     ,year_bud_app         decimal(18,6)    comment'年初预算审批版'
     ,bud_dev              decimal(18,6)  comment'预算偏差'
     ,bud_fin              decimal(18,6)  comment'预算达成率'
     ,last_y_curmonth      decimal(18,6)  comment'去年当月实际'
     ,fac_inc_amt          decimal(18,6)  comment'实际增长额'
     ,fac_inc_rate         decimal(18,6)   comment'实际增长率'
     ,cur_y_sum            decimal(18,6)   comment'本年实际累计'
     ,year_bud_sum         decimal(18,6)   comment'累计年初预算'
     ,bud_dev_sum          decimal(18,6)   comment'预算累计偏差(实际累计-累计年初预算)'
     ,bud_sum_rate         decimal(18,6)   comment'预算累计达成率'
     ,last_y_sum           decimal(18,6)   comment'去年实际累计'
     ,fac_inc_amt_sum      decimal(18,6)   comment'累计实际增长额(实际累计-去年累计)'
     ,fac_inc_rate_sum     decimal(18,6)   comment'累计实际增长率（累计实际增长额/实际累计）'
     ,all_y_bud            decimal(18,6)   comment'全年预估'
     ,all_y_bud_app        decimal(18,6)   comment'全年年初预算审批'
     ,all_y_bud_dev        decimal(18,6)   comment'全年预估偏差(全年预估-全年年初预算审批)'
     ,all_y_bud_rate       decimal(18,6)   comment'全年预估达成率(全年预估偏差/全年年初预算审批)'
     ,last_y_fac           decimal(18,6)   comment'去年全年实际'
     ,all_y_bud_inc_amt    decimal(18,6)   comment'全年预估增长额(全年预估-去年全年实际)'
     ,all_y_bud_inc_rate   decimal(18,6)   comment'全年预估增长率'
     ,version              varchar(50)    comment '版本'
     ,type                 varchar(50)    comment '类型'
     
  ,create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
  ,update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
  , primary key (the_month,projectname,regionname,expenditureid) 
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目财务表'
  ;