use ${HIVE_DB_APP};
CREATE TABLE a05_brand_index(
`the_month`                   string              comment '年月'
,`projectguid`                string              comment '项目guid'
,`mainformatid`               string              comment '业态id'
,`branddesc`                  string              comment '品牌名称'
,`city`                       string              comment '城市名'
,`province`                   string              comment '省份名'
,`district_name`              string              comment '片区名称'
,`companyid`                  string              comment '地区id'
,`companyguid`                string              comment '地区guid'
,`companyname`                string              comment '地区名称'
,`projectopen_date`           string              comment '项目开业日期'
,`is_preparatory_period`      string              comment '是否筹备期'
,`is_storage_project`         string              comment '是否存量项目'
,`saleamt`                    double              comment '营业额'
,`bg_saleamt`                 double              comment '预算营业额'
,`salenum`                    bigint              comment '营业笔数'
,`mng_fee`                   decimal(18,6)    comment '预算推广服务费'
,`rentfee`                    decimal(18,6)    comment '预算保底租金'
,`promotivefee`            decimal(18,6)    comment '预算物业管理费'
,`revenufee`               decimal(18,6)    comment '预算抽成租金'
,`bd_income_y`                 decimal(18,6)       comment '租金_含税保底租金'
,`taking_income_y`            decimal(18,6)       comment '租金_含税抽成租金'
,`mng_income_y`               decimal(18,6)       comment '租金_含税物业管理费'
,`tg_income_y`                decimal(18,6)       comment '租金_含税推广服务费'
,`bd_income_n`                decimal(18,6)       comment '租金_不含税保底租金'
,`taking_income_n`            decimal(18,6)       comment '租金_不含税抽成租金'
,`mng_income_n`               decimal(18,6)       comment '租金_不含税物业管理费'
,`tg_income_n`                decimal(18,6)       comment '租金_不含税推广服务费'
,`totalarea`                  decimal(18,6)       comment '接铺面积'
,`project_rent_area`          decimal(18,6)       comment '项目可出租面积'
,`op_time`                    string              comment '时间戳'
,`execution_id`               bigint              comment '批次号'
,load_date                    string              comment '入库时间'
)
comment '会员品牌指标表'
partitioned by
 (`datekey` string comment '年月分区')
STORED AS PARQUET;