use ${HIVE_DB_DWS};
CREATE TABLE dws.f20_spider_house_all_merge(
       room_id            string comment '房屋id'
      ,village_id         string comment '小区/公寓项目id'
      ,village            string comment '小区/公寓项目名称'
      ,apartment_name     string comment '公寓名称'
      ,city               string comment '城市'
      ,location_region    string comment '地区'
      ,location_center    string comment '板块'
      ,min_area           string comment '最小建筑面积'
      ,max_area           string comment '最大建筑面积'
      ,towards            string comment '朝向'
      ,has_subway         string comment '是否有地铁'
      ,subway_num         string comment '地铁数目'
      ,subway_dist        string comment '地铁距离'
      ,subway_name        string comment '地铁站名'
      ,row_wid_subway     string comment '地铁id'
      ,subway_center      string comment '地铁商圈'
      ,subway_lines       string comment '地铁线路'
      ,total_floor        string comment '总楼层'
      ,relative_floor     string comment '相对楼层'
      ,model              string comment '居室'
      ,model_rooms        string comment '室'
      ,model_halls        string comment '厅'
      ,model_kitchen      string comment '厨'
      ,model_bathrooms    string comment '卫'
      ,time               string comment '抓取日期'
      ,datekey            string comment '抓取日期'
      ,min_price          string comment '最低价格'
      ,max_price          string comment '最高价格'
      ,price              string comment '价格'
      ,overall_qual       string comment '装修程度'
      ,trade_type         string comment '类型：买卖；整租；合租'
      ,unitprice          string comment '单价（元/平）'
      ,lon                string comment '小区经度'
      ,lat                string comment '小区纬度'
      ,build_year         string comment '小区建筑年代'
      ,village_households string comment '小区户数'
      ,brand_name         string comment '品牌(只有湾流有)'
      ,table_name         string comment '来源表'
      ,op_time      string comment 'op_time'
      ,execution_id string comment '执行批次'
      ,load_date    string comment '入库时间'
)
  comment '爬虫抓取的小区房屋信息表_全量快照'
   PARTITIONED BY (
  part_week string)
STORED AS PARQUET;
